spring:
  application:
    name: animal
  datasource:
    url: jdbc:postgresql://localhost:5432/animals_db
    username: gapushin
    password: 12345
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
    schema: example
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none